name: codenames

services:
  codenames-server:
    container_name: codenames_server
    image: codenames-server:latest
    ports:
      - ${FLASK_PORT:-5000}:5000
    env_file:
      - .env
    environment:
      GAME_MODE: ${GAME_MODE:-custom}
      IMAGE_DIR: /app/images
    volumes:
      - ${IMAGE_DIR}:/app/images
