version: '3.8'
services:
  client:
    image: creator-client:latest
    ports:
      - "3000:3000"
  server:
    image: creator-server:latest
    ports:
      - "5000:5000"
    environment:
      GAME_MODE: ${GAME_MODE}
      IMAGE_DIR: /app/images
    env_file:
      - .env
    volumes:
      - ${IMAGE_DIR}:/app/images
  proxy:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9000:9000
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
